# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiveDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_frame_honey', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('first_frame_speck', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('first_frame_beebread', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('first_frame_worm', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('second_frame_honey', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('second_frame_speck', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('second_frame_beebread', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('second_frame_worm', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('third_frame_honey', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('third_frame_speck', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('third_frame_beebread', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('third_frame_worm', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('fourth_frame_honey', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('fourth_frame_speck', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('fourth_frame_beebread', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('fourth_frame_worm', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('fifth_frame_honey', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('fifth_frame_speck', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('fifth_frame_beebread', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('fifth_frame_worm', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('sixth_frame_honey', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('sixth_frame_speck', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('sixth_frame_beebread', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('sixth_frame_worm', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('seventh_frame_honey', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('seventh_frame_speck', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('seventh_frame_beebread', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('seventh_frame_worm', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('eight_frame_honey', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('eight_frame_speck', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('eight_frame_beebread', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('eight_frame_worm', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('ninth_frame_honey', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('ninth_frame_speck', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('ninth_frame_beebread', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('ninth_frame_worm', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('tenth_frame_honey', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('tenth_frame_speck', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('tenth_frame_beebread', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('tenth_frame_worm', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('addDate', models.DateField(auto_now_add=True)),
                ('motherBee', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HiveModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfHive', models.IntegerField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('additional_info', models.CharField(max_length=500, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hivedatamodel',
            name='hive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hives.HiveModel'),
        ),
    ]
