# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0002_auto_20180913_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsthivedatamodel',
            name='third_frame_worm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
