# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0002_auto_20180903_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivemodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
