# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0009_auto_20181101_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivemodel',
            name='numberOfHive',
            field=models.IntegerField(),
        ),
    ]
