# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0011_firsthivedatamodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firsthivedatamodel',
            name='owner',
        ),
    ]
