# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0013_firsthivedatamodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='firsthivedatamodel',
            name='hiver_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='firsthivedatamodel',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
