# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0016_firsthivedatamodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firsthivedatamodel',
            name='hiver_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
