# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-08 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0017_auto_20181102_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourthhivedatamodel',
            name='hiver_id',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AddField(
            model_name='secondhivedatamodel',
            name='hiver_id',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='thirdhivedatamodel',
            name='hiver_id',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AlterField(
            model_name='firsthivedatamodel',
            name='owner',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='fourthhivedatamodel',
            name='owner',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='secondhivedatamodel',
            name='owner',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdhivedatamodel',
            name='owner',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
